### ISSUE TITLE
Tweak Rules

### ISSUE THREAD

**Issue by nicholasio** [10up/eslint-config#20]
**Is your enhancement related to a problem? Please describe.**
This issue aims at listing some rules we might want to tweak or disable based on our experience at 10up.

**Describe the solution you'd like**

- Add `"allowForLoopAfterthoughts": true` to `no-plus-plus` - see https://github.com/10up/Engineering-Best-Practices/pull/331#discussion_r438083361
- Disable prefer-destructing for arrays (`'prefer-destructuring': [2, { array: false, object: true } ],`) as it can lead to a weird syntax
- "import/no-extraneous-dependencies": ["error", {"devDependencies": true}]
- no-param-reassign
```
let myvar= 'some value';
// logic...
[myvar] = array; // instead of myvar= array[0]
```

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by tlovett1** [comment]
@nicholasio I noticed you can't do `while ( true ) { ....` IMO that's pretty important.

**Comment by nicholasio** [comment]
> @nicholasio I noticed you can't do `while ( true ) { ....` IMO that's pretty important.

I understand use cases (like just looping indefinitely until getting all posts in a database for example like what we do a lot in wp-cli), but I'm not sure if doing something like that would be necessary in the js/client-side land, generally there are better strategies using promises/iterators/generators. Do you have an example of what you're thinking? 

It is possible to disable the `no-constant-condition` for loops by setting `checkLoops` to false. https://eslint.org/docs/rules/no-constant-condition#checkloops
