### ISSUE TITLE
Configuration for rule "jsdoc/require-param" is invalid

### ISSUE THREAD

**Issue by darylldoyle** [10up/eslint-config#31]
**Describe the bug**
I've just created a new plugin using the 10up-create scaffold and when I run any npm commands I get the following error:

```
Error: .eslintrc.json » @10up/eslint-config/wordpress » ./react » ./index » /path/to/plugin/node_modules/@10up/eslint-config/rules/jsdoc.js:
        Configuration for rule "jsdoc/require-param" is invalid:
        Value {"enableFixer":false} should NOT have additional properties.

```
I'm guessing this was introduced in https://github.com/10up/eslint-config/commit/6b9338c23f181a88d57dd8725d95fcbd3fd79b65. 

**Steps to Reproduce**
1. `10up-create plugin test`
2. `cd test`
3. `npm run start`

**Expected behavior**
`npm run x` commands should complete without error.

**Comment by nicholasio** [comment]
Can you  try running `npx install-peerdeps --dev @10up/eslint-config` I believe the dependencies eslint needs are not updated in the scaffold.

**Comment by nicoladj77** [comment]
I'm having the issue too when linting. Maybe something has changed and the {"enableFixer":false} is not accepted anymore

**Comment by nicholasio** [comment]
@nicoladj77 can you try running the command above to update deps or update the eslint-plugin-jsdoc manually?

**Comment by nicoladj77** [comment]
@nicholasio tried to update deps and got

C:\Users\nicol\wp-local-docker-sites\nobel-test\wordpress\wp-content\plugins\nobelprize-block-library [feature/18858536-plugin-setup +61 ~6 -0 ~]>npx install-peerdeps --dev @10up/eslint-config
install-peerdeps v3.0.3
Installing peerdeps for @10up/eslint-config@latest.
npm install @10up/eslint-config@2.3.2 @babel/core@^7.2.0 @babel/eslint-parser@^7.12.13 eslint@^7.2.0 eslint-config-airbnb@^18.2.1 eslint-config-airbnb-base@^14.2.1 eslint-config-prettier@^7.1.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsdoc@^31.2.0 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-prettier@^3.3.1 eslint-plugin-react@^7.22.0 eslint-plugin-react-hooks@^1.7.0 prettier@^2.2.1 --save-dev

ERR undefined

**Comment by nicoladj77** [comment]
After that it was still failing

**Comment by nicholasio** [comment]
I'll look into this, we're using latest eslint config on 10up scripts and it's working fine. In the meantime, you can just disable this rule

**Comment by mateus4k** [comment]
> @nicholasio tried to update deps and got
> 
> C:\Users\nicol\wp-local-docker-sites\nobel-test\wordpress\wp-content\plugins\nobelprize-block-library [feature/18858536-plugin-setup +61 ~6 -0 ~]>npx install-peerdeps --dev @10up/eslint-config
> install-peerdeps v3.0.3
> Installing peerdeps for @10up/eslint-config@latest.
> npm install @10up/eslint-config@2.3.2 @babel/core@^7.2.0 @babel/eslint-parser@^7.12.13 eslint@^7.2.0 eslint-config-airbnb@^18.2.1 eslint-config-airbnb-base@^14.2.1 eslint-config-prettier@^7.1.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsdoc@^31.2.0 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-prettier@^3.3.1 eslint-plugin-react@^7.22.0 eslint-plugin-react-hooks@^1.7.0 prettier@^2.2.1 --save-dev
> 
> ERR undefined

You can try running the script generated by peerdeps adding the `--legacy-peer-deps` flag:
```sh
npm install -D --legacy-peer-deps @10up/eslint-config@2.3.2 @babel/core@^7.2.0 @babel/eslint-parser@^7.12.13 eslint@^7.2.0 eslint-config-airbnb@^18.2.1 eslint-config-airbnb-base@^14.2.1 eslint-config-prettier@^7.1.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsdoc@^31.2.0 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-prettier@^3.3.1 eslint-plugin-react@^7.22.0 eslint-plugin-react-hooks@^1.7.0 prettier@^2.2.1
```
And then add this to your `.eslintrc.js`

```js
overrides: [
  {
    files: ['*.js']
    rules: {
      'jsdoc/require-param': 'off'
    },
  },
]
```

It worked for me 🙂

**Comment by nicholasio** [comment]
@mateus4k Are you running npm 7? Did you get the issue even after updating all deps?

The `enableFixer` is a supported option in the latest eslint-plugin-jsdoc https://github.com/gajus/eslint-plugin-jsdoc/blob/master/.README/rules/require-param.md#enablefixer

**Comment by nicholasio** [comment]
Closing this as it's related to an old version of `eslint-plugin-jsdoc`, for anyone having this issue, just manually update this dep to the latest version.
