### ISSUE TITLE
React projects support

### ISSUE THREAD

**Issue by eugene-manuilov** [10up/eslint-config#6]
This config doesn't seem to be working with react projects. Is there an easy way to make it work together? 

The current config doesn't recognize jsx and thinks that `import React from 'react';` is unused variable.

**Comment by saltcod** [comment]
Sorted for the moment via: 

{
  "extends": [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended",
  ],
  "rules": {
    "react/prop-types": 0
  },
  "plugins": ["react", "import", "jsx-a11y"],
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "globals": {
    "React": true
  }
}



I'll try and put together a PR that addresses this in the repo, or repo(s) if we feel like we need a separate one for React.

**Comment by samikeijonen** [comment]
With Gutenberg there is now [@wordpress/eslint-plugin](https://www.npmjs.com/package/@wordpress/eslint-plugin). Supports

- es5
- esnext
- jsx-a11y
- react

depending on you project type. This might be a good option to base 10up lint rules using this one.

**Comment by nicholasio** [comment]
We now have official react support in the new version of this config.
