### ISSUE TITLE
Configure package.json to install dependencies.

### ISSUE THREAD

**Issue by kopepasah** [10up/eslint-config#9]
This node package has two dependencies which are not defined in `package.json` as dependencies: `eslint` and `babel-eslint`. As such, these dependencies are not installed when running `npm install @10up/eslint-config` and running `eslint` throws an error.

**Comment by eugene-manuilov** [comment]
@kopepasah my understanding is that this package is a config and intended to just keep eslint settings. How it is going to be used is out of the scope for this package, thus it shouldn't install 3rd party plugins, imho.

**Comment by kopepasah** [comment]
@eugene-manuilov the config itself has dependencies. For example, if I install this config — a per the directions — and run `./node_modules/.bin/eslint` on a fresh project, it will fail because `eslint` is not installed. Secondly, if I do happen to install `eslint` on the project prior to installing this "config", the `eslint` command will fail because because it is missing the `babel-eslint` dependency.

Sure, we can call this a "config", but in reality it is a Node Package and all Node Package's should reference dependencies correctly to prevent failures.

**Comment by kopepasah** [comment]
Essentially, the only way to successfully install and run this package is to install all three packages:

```
npm i -D @10up/eslint-config eslint bable-eslint
                              👆🏻      👆🏻
                              Dependencies
```

**Comment by eugene-manuilov** [comment]
@kopepasah two questions:

1. What if i don't use babel on my project, why do i need to install `babel-eslint` dependency?
1. What if I already have `eslint` and `babel-eslint` as top level dependencies in my package.json config but their version is different from what you propose to add in the `@10up/eslint-config` package?

In the first case i will have to install useless dependency. In the second case i will have to install two different versions of eslint because this is how npm [works](http://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html). 

There is nothing hard to install 3 dependencies all together when you define your dependencies by running `npm i @10up/eslint-config eslint bable-eslint`.

As an alternative we can probably add `eslint` as a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/). In this case npm will tell you that you are missing it if you haven't installed it yet.

**Comment by kopepasah** [comment]
> 1. What if i don't use babel on my project, why do i need to install babel-eslint dependency?

This package __requires__ `babel-eslint` (see [here](https://github.com/10up/eslint-config/blob/master/.eslintrc#L2)).

> 2. What if I already have eslint and babel-eslint as top level dependencies in my package.json config but their versions are different from what you propose to add in the @10up/eslint-config package?
In the first case i will have to install useless dependency. In the second case i will have to install two different versions of eslint because this is how npm works.

Your ESLint config package should define which version of ESLint it expects, not vice versa.

> There is nothing hard to install 3 dependencies all together when you define your dependencies by running npm i @10up/eslint-config eslint bable-eslint.

This is not how Node is built to work. Dependencies of a package should be installed any time that package is installed. 

> As an alternative we can probably add eslint as a peer dependency. In this case npm will tell you that you are missing it if you haven't installed it yet.

While this is possible, it is not the correct solution. This package is an ESLint config with the expectation that ESLint will lint the JavaScript within the project. I cannot think of any cases where this package would conflict with other uses of ESLint on the project (as there should be no reason to run multiple JavaScript linters). Can you give me an example where we might need to run multiple versions of ESLint?

**Comment by eugene-manuilov** [comment]
> This package requires babel-eslint

Hm... i haven't known that we use `babel-eslint` as parser for the config... why do we use it there and what issues does it solve? If it's required, then I agree that it has to be in the dependencies list.

> While this is possible, it is not the correct solution.

I won't argue anymore, just going to say that in my opinion it must be a peer dependency at best. Check the [list](https://github.com/dustinspecker/awesome-eslint#configs) of eslint configs from Airbnb, Google, Facebook, Shopify, etc. There is only one config (for Supermind style) out of eleven that defines eslint as a dependency explicitly. Every one else declares it as a peer dependency.

**Comment by kopepasah** [comment]
@eugene-manuilov actually, I am not certain why this package relies on `babel-eslint`, but I guess it has something to do with the scaffolds. From my understanding, this package is heavily centered around the scaffolds and that is the reason these are dependencies.

Regarding defining as a peer dependency, I too feel we should go your route. Thanks for doing that extra research! Can you make that change on the source branch for the pull request?

**Comment by nicholasio** [comment]
This was solved with the `npx install-peerdeps --dev @10up/eslint-config` command which installs all peer dependencies.
